apiVersion: v1
kind: Service
metadata:
  name: dealership
  labels:
    app: dealership
spec:
  type: NodePort
  selector:
    app: dealership
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
